# -*- coding: utf-8 -*-
"""Financial Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1puqKjPxR2bSJs6U0HJW0RfVp5dIzV6ST
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded = files.upload()

data=pd.read_csv("/content/Financial Analytics data.csv")
print(data)

data.describe()

data.info()

data.isnull().sum()

df=data.drop(['Unnamed: 4'],axis=1)

df

df1=df.dropna()
df1=df1.reset_index()
df1

df1['Name'].unique()

plt.figure(figsize=(100,20))
plt.bar(df1['Name'],df1["Mar Cap - Crore"])
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(100,20))
plt.bar(df1['Name'],df1["Sales Qtr - Crore"])
plt.xticks(rotation=45)
plt.show()

"""**Correlation graph of all variables**

"""

cor=data.corr()
plt.figure(figsize=(12,10))
sns.heatmap(cor,linewidth=1,annot=True,linecolor='black')